### ISSUE TITLE
How to use module

### ISSUE THREAD

**Issue by mzenner1** [springimport/magento2-module-constantcontact#1]
I've installed the module and entered the Key and Access Token.  What is the next step to feed a newsletter subscription to a campaign in constant contact?

**Comment by springimport** [comment]
@mzenner1 This magento 2 module is only wrapper for official ConstantContact SDK. For working solution you need to create your module.

**Comment by mzenner1** [comment]
Yep, I quickly figured that out.  I got a module in place.  Thanks for the reply!

**Comment by springimport** [comment]
@mzenner1 Good luck!
